package models;
// Generated on the Jul 31, 2013 1:54:11 PM by Play!

import play.db.jpa.JPASupport;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WpCommentmeta generated by Play!
 */
@Entity
@Table(name="wp_commentmeta"
    ,catalog="wpEvent"
    , uniqueConstraints = {  }
)
public class WpCommentmeta extends JPASupport implements java.io.Serializable {

    // Fields

     @Id
    
    @Column(name="meta_id", unique=true, nullable=false, insertable=true, updatable=true)
        public long metaId;
    
    @Column(name="comment_id", unique=false, nullable=false, insertable=true, updatable=true)
        public long commentId;
    
    @Column(name="meta_key", unique=false, nullable=true, insertable=true, updatable=true)
        public String metaKey;
    
    @Column(name="meta_value", unique=false, nullable=true, insertable=true, updatable=true)
        public String metaValue;
     // Constructors

    /** default constructor */
    public WpCommentmeta() {
    }

	/** minimal constructor */
    public WpCommentmeta(long metaId, long commentId) {
        this.metaId = metaId;
        this.commentId = commentId;
    }
    /** full constructor */
    public WpCommentmeta(long metaId, long commentId, String metaKey, String metaValue) {
       this.metaId = metaId;
       this.commentId = commentId;
       this.metaKey = metaKey;
       this.metaValue = metaValue;
    }
   


}


