package models;
// Generated on the Jul 31, 2013 1:54:11 PM by Play!

import play.db.jpa.JPASupport;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WpComments generated by Play!
 */
@Entity
@Table(name="wp_comments"
    ,catalog="wpEvent"
    , uniqueConstraints = {  }
)
public class WpComments extends JPASupport implements java.io.Serializable {

    // Fields

     @Id
    
    @Column(name="comment_ID", unique=true, nullable=false, insertable=true, updatable=true)
        public long commentId;
    
    @Column(name="comment_post_ID", unique=false, nullable=false, insertable=true, updatable=true)
        public long commentPostId;
    
    @Column(name="comment_author", unique=false, nullable=false, insertable=true, updatable=true)
        public String commentAuthor;
    
    @Column(name="comment_author_email", unique=false, nullable=false, insertable=true, updatable=true, length=100)
        public String commentAuthorEmail;
    
    @Column(name="comment_author_url", unique=false, nullable=false, insertable=true, updatable=true, length=200)
        public String commentAuthorUrl;
    
    @Column(name="comment_author_IP", unique=false, nullable=false, insertable=true, updatable=true, length=100)
        public String commentAuthorIp;
    
    @Column(name="comment_date", unique=false, nullable=false, insertable=true, updatable=true, length=19)
        public Date commentDate;
    
    @Column(name="comment_date_gmt", unique=false, nullable=false, insertable=true, updatable=true, length=19)
        public Date commentDateGmt;
    
    @Column(name="comment_content", unique=false, nullable=false, insertable=true, updatable=true, length=65535)
        public String commentContent;
    
    @Column(name="comment_karma", unique=false, nullable=false, insertable=true, updatable=true)
        public int commentKarma;
    
    @Column(name="comment_approved", unique=false, nullable=false, insertable=true, updatable=true, length=20)
        public String commentApproved;
    
    @Column(name="comment_agent", unique=false, nullable=false, insertable=true, updatable=true)
        public String commentAgent;
    
    @Column(name="comment_type", unique=false, nullable=false, insertable=true, updatable=true, length=20)
        public String commentType;
    
    @Column(name="comment_parent", unique=false, nullable=false, insertable=true, updatable=true)
        public long commentParent;
    
    @Column(name="user_id", unique=false, nullable=false, insertable=true, updatable=true)
        public long userId;
     // Constructors

    /** default constructor */
    public WpComments() {
    }

    /** full constructor */
    public WpComments(long commentId, long commentPostId, String commentAuthor, String commentAuthorEmail, String commentAuthorUrl, String commentAuthorIp, Date commentDate, Date commentDateGmt, String commentContent, int commentKarma, String commentApproved, String commentAgent, String commentType, long commentParent, long userId) {
       this.commentId = commentId;
       this.commentPostId = commentPostId;
       this.commentAuthor = commentAuthor;
       this.commentAuthorEmail = commentAuthorEmail;
       this.commentAuthorUrl = commentAuthorUrl;
       this.commentAuthorIp = commentAuthorIp;
       this.commentDate = commentDate;
       this.commentDateGmt = commentDateGmt;
       this.commentContent = commentContent;
       this.commentKarma = commentKarma;
       this.commentApproved = commentApproved;
       this.commentAgent = commentAgent;
       this.commentType = commentType;
       this.commentParent = commentParent;
       this.userId = userId;
    }
   


}


