package models;
// Generated on the Jul 31, 2013 1:54:11 PM by Play!

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import play.db.jpa.Model;

/**
 * WpOptions generated by Play!
 */
@Entity
@Table(name="wp_options"
    ,catalog="wpEvent"
    , uniqueConstraints = { @UniqueConstraint( columnNames = { "option_name" } ) }
)
public class WpOptions extends Model implements java.io.Serializable {

    // Fields

     @Id
    
    @Column(name="option_id", unique=true, nullable=false, insertable=true, updatable=true)
        public long optionId;
    
    @Column(name="option_name", unique=true, nullable=false, insertable=true, updatable=true, length=64)
        public String optionName;
    
    @Column(name="option_value", unique=false, nullable=false, insertable=true, updatable=true)
        public String optionValue;
    
    @Column(name="autoload", unique=false, nullable=false, insertable=true, updatable=true, length=20)
        public String autoload;
     // Constructors

    /** default constructor */
    public WpOptions() {
    }

    /** full constructor */
    public WpOptions(long optionId, String optionName, String optionValue, String autoload) {
       this.optionId = optionId;
       this.optionName = optionName;
       this.optionValue = optionValue;
       this.autoload = autoload;
    }
   


}


