package models;
// Generated on the Jul 31, 2013 1:54:11 PM by Play!

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import play.db.jpa.Model;

/**
 * WpPostmeta generated by Play!
 */
@Entity
@Table(name="wp_postmeta"
    ,catalog="wpEvent"
    , uniqueConstraints = {  }
)
public class WpPostmeta extends Model implements java.io.Serializable {

    // Fields

     @Id
    
    @Column(name="meta_id", unique=true, nullable=false, insertable=true, updatable=true)
        public long metaId;
    
    @Column(name="post_id", unique=false, nullable=false, insertable=true, updatable=true)
        public long postId;
    
    @Column(name="meta_key", unique=false, nullable=true, insertable=true, updatable=true)
        public String metaKey;
    
    @Column(name="meta_value", unique=false, nullable=true, insertable=true, updatable=true)
        public String metaValue;
     // Constructors

    /** default constructor */
    public WpPostmeta() {
    }

	/** minimal constructor */
    public WpPostmeta(long metaId, long postId) {
        this.metaId = metaId;
        this.postId = postId;
    }
    /** full constructor */
    public WpPostmeta(long metaId, long postId, String metaKey, String metaValue) {
       this.metaId = metaId;
       this.postId = postId;
       this.metaKey = metaKey;
       this.metaValue = metaValue;
    }
   


}


