package models;
// Generated on the Jul 31, 2013 1:54:11 PM by Play!

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import play.db.jpa.Model;

/**
 * WpPosts generated by Play!
 */
@Entity
@Table(name="wp_posts"
    ,catalog="wpEvent"
    , uniqueConstraints = {  }
)
public class WpPosts extends Model implements java.io.Serializable {

    // Fields
 
    @Column(name="post_author", unique=false, nullable=false, insertable=true, updatable=true)
        public long postAuthor;
    
    @Column(name="post_date", unique=false, nullable=false, insertable=true, updatable=true, length=19)
        public Date postDate;
    
    @Column(name="post_date_gmt", unique=false, nullable=false, insertable=true, updatable=true, length=19)
        public Date postDateGmt;
    
    @Column(name="post_content", unique=false, nullable=false, insertable=true, updatable=true)
        public String postContent;
    
    @Column(name="post_title", unique=false, nullable=false, insertable=true, updatable=true, length=65535)
        public String postTitle;
    
    @Column(name="post_excerpt", unique=false, nullable=false, insertable=true, updatable=true, length=65535)
        public String postExcerpt;
    
    @Column(name="post_status", unique=false, nullable=false, insertable=true, updatable=true, length=20)
        public String postStatus;
    
    @Column(name="comment_status", unique=false, nullable=false, insertable=true, updatable=true, length=20)
        public String commentStatus;
    
    @Column(name="ping_status", unique=false, nullable=false, insertable=true, updatable=true, length=20)
        public String pingStatus;
    
    @Column(name="post_password", unique=false, nullable=false, insertable=true, updatable=true, length=20)
        public String postPassword;
    
    @Column(name="post_name", unique=false, nullable=false, insertable=true, updatable=true, length=200)
        public String postName;
    
    @Column(name="to_ping", unique=false, nullable=false, insertable=true, updatable=true, length=65535)
        public String toPing;
    
    @Column(name="pinged", unique=false, nullable=false, insertable=true, updatable=true, length=65535)
        public String pinged;
    
    @Column(name="post_modified", unique=false, nullable=false, insertable=true, updatable=true, length=19)
        public Date postModified;
    
    @Column(name="post_modified_gmt", unique=false, nullable=false, insertable=true, updatable=true, length=19)
        public Date postModifiedGmt;
    
    @Column(name="post_content_filtered", unique=false, nullable=false, insertable=true, updatable=true)
        public String postContentFiltered;
    
    @Column(name="post_parent", unique=false, nullable=false, insertable=true, updatable=true)
        public long postParent;
    
    @Column(name="guid", unique=false, nullable=false, insertable=true, updatable=true)
        public String guid;
    
    @Column(name="menu_order", unique=false, nullable=false, insertable=true, updatable=true)
        public int menuOrder;
    
    @Column(name="post_type", unique=false, nullable=false, insertable=true, updatable=true, length=20)
        public String postType;
    
    @Column(name="post_mime_type", unique=false, nullable=false, insertable=true, updatable=true, length=100)
        public String postMimeType;
    
    @Column(name="comment_count", unique=false, nullable=false, insertable=true, updatable=true)
        public long commentCount;
     // Constructors

    /** default constructor */
    public WpPosts() {
    }

    /** full constructor */
    public WpPosts(long id, long postAuthor, Date postDate, Date postDateGmt, String postContent, String postTitle, String postExcerpt, String postStatus, String commentStatus, String pingStatus, String postPassword, String postName, String toPing, String pinged, Date postModified, Date postModifiedGmt, String postContentFiltered, long postParent, String guid, int menuOrder, String postType, String postMimeType, long commentCount) {
       this.id = id;
       this.postAuthor = postAuthor;
       this.postDate = postDate;
       this.postDateGmt = postDateGmt;
       this.postContent = postContent;
       this.postTitle = postTitle;
       this.postExcerpt = postExcerpt;
       this.postStatus = postStatus;
       this.commentStatus = commentStatus;
       this.pingStatus = pingStatus;
       this.postPassword = postPassword;
       this.postName = postName;
       this.toPing = toPing;
       this.pinged = pinged;
       this.postModified = postModified;
       this.postModifiedGmt = postModifiedGmt;
       this.postContentFiltered = postContentFiltered;
       this.postParent = postParent;
       this.guid = guid;
       this.menuOrder = menuOrder;
       this.postType = postType;
       this.postMimeType = postMimeType;
       this.commentCount = commentCount;
    }
    
    @Override
    public String toString() {
    	return postContent;
    }
   


}


