package models;
// Generated on the Jul 31, 2013 1:54:11 PM by Play!

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import play.db.jpa.Model;

/**
 * WpTermRelationships generated by Play!
 */
@Entity
@Table(name="wp_term_relationships"
    ,catalog="wpEvent"
    , uniqueConstraints = {  }
)
public class WpTermRelationships extends Model implements java.io.Serializable {

    // Fields

     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="objectId", column=@Column(name="object_id", unique=false, nullable=false, insertable=true, updatable=true) ), 
        @AttributeOverride(name="termTaxonomyId", column=@Column(name="term_taxonomy_id", unique=false, nullable=false, insertable=true, updatable=true) ) } )
        public WpTermRelationshipsId id;
    
    @Column(name="term_order", unique=false, nullable=false, insertable=true, updatable=true)
        public int termOrder;
     // Constructors

    /** default constructor */
    public WpTermRelationships() {
    }

    /** full constructor */
    public WpTermRelationships(WpTermRelationshipsId id, int termOrder) {
       this.id = id;
       this.termOrder = termOrder;
    }
   


}


