package models;
// Generated on the Jul 31, 2013 1:54:11 PM by Play!

import play.db.jpa.JPASupport;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WpUsermeta generated by Play!
 */
@Entity
@Table(name="wp_usermeta"
    ,catalog="wpEvent"
    , uniqueConstraints = {  }
)
public class WpUsermeta extends JPASupport implements java.io.Serializable {

    // Fields

     @Id
    
    @Column(name="umeta_id", unique=true, nullable=false, insertable=true, updatable=true)
        public long umetaId;
    
    @Column(name="user_id", unique=false, nullable=false, insertable=true, updatable=true)
        public long userId;
    
    @Column(name="meta_key", unique=false, nullable=true, insertable=true, updatable=true)
        public String metaKey;
    
    @Column(name="meta_value", unique=false, nullable=true, insertable=true, updatable=true)
        public String metaValue;
     // Constructors

    /** default constructor */
    public WpUsermeta() {
    }

	/** minimal constructor */
    public WpUsermeta(long umetaId, long userId) {
        this.umetaId = umetaId;
        this.userId = userId;
    }
    /** full constructor */
    public WpUsermeta(long umetaId, long userId, String metaKey, String metaValue) {
       this.umetaId = umetaId;
       this.userId = userId;
       this.metaKey = metaKey;
       this.metaValue = metaValue;
    }
   


}


