package models;
// Generated on the Jul 31, 2013 1:54:11 PM by Play!

import play.db.jpa.JPASupport;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WpUsers generated by Play!
 */
@Entity
@Table(name="wp_users"
    ,catalog="wpEvent"
    , uniqueConstraints = {  }
)
public class WpUsers extends JPASupport implements java.io.Serializable {

    // Fields

     @Id
    
    @Column(name="ID", unique=true, nullable=false, insertable=true, updatable=true)
        public long id;
    
    @Column(name="user_login", unique=false, nullable=false, insertable=true, updatable=true, length=60)
        public String userLogin;
    
    @Column(name="user_pass", unique=false, nullable=false, insertable=true, updatable=true, length=64)
        public String userPass;
    
    @Column(name="user_nicename", unique=false, nullable=false, insertable=true, updatable=true, length=50)
        public String userNicename;
    
    @Column(name="user_email", unique=false, nullable=false, insertable=true, updatable=true, length=100)
        public String userEmail;
    
    @Column(name="user_url", unique=false, nullable=false, insertable=true, updatable=true, length=100)
        public String userUrl;
    
    @Column(name="user_registered", unique=false, nullable=false, insertable=true, updatable=true, length=19)
        public Date userRegistered;
    
    @Column(name="user_activation_key", unique=false, nullable=false, insertable=true, updatable=true, length=60)
        public String userActivationKey;
    
    @Column(name="user_status", unique=false, nullable=false, insertable=true, updatable=true)
        public int userStatus;
    
    @Column(name="display_name", unique=false, nullable=false, insertable=true, updatable=true, length=250)
        public String displayName;
     // Constructors

    /** default constructor */
    public WpUsers() {
    }

    /** full constructor */
    public WpUsers(long id, String userLogin, String userPass, String userNicename, String userEmail, String userUrl, Date userRegistered, String userActivationKey, int userStatus, String displayName) {
       this.id = id;
       this.userLogin = userLogin;
       this.userPass = userPass;
       this.userNicename = userNicename;
       this.userEmail = userEmail;
       this.userUrl = userUrl;
       this.userRegistered = userRegistered;
       this.userActivationKey = userActivationKey;
       this.userStatus = userStatus;
       this.displayName = displayName;
    }
   


}


